language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - vendor

before_script:
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/atoum --test-ext -ulr
